// Phase 2.16 — seeded default-tier validation rules (societyId: null). Each
// `rule` key must exist in CHECK_REGISTRY (lib/accounting/validation/checks.js).
// Mirrors the shape/seeding convention of DEFAULT_POSTING_RULES
// (lib/accounting/postingRules/defaultRules.js).

export const DEFAULT_VALIDATION_RULES = [
  {
    systemKey: "default:TrialBalanceBalanced",
    rule: "trialBalanceBalanced",
    description: "Trial Balance debit total must equal credit total",
    severity: "Error",
    blocking: true,
    navigationTarget: "/accounting/trial-balance",
    helpText: "The Trial Balance for this Financial Year does not balance.",
    suggestedResolution: "Review recent vouchers for an unbalanced or missing Journal Entry.",
  },
  {
    systemKey: "default:AccountsMissingScheduleCode",
    rule: "accountsMissingScheduleCode",
    description: "Active accounts must have a Balance Sheet scheduleCode",
    severity: "Warning",
    blocking: true,
    navigationTarget: "/accounting/chart-of-accounts",
    helpText: "An account with no scheduleCode will be silently misplaced (or omitted) on the Balance Sheet.",
    suggestedResolution: "Set a scheduleCode on every active account before generating financial statements.",
  },
  {
    systemKey: "default:UnmappedDefaultAccountMappings",
    rule: "unmappedDefaultAccountMappings",
    description: "Default account mappings must be configured once accounting is enabled",
    severity: "Error",
    blocking: true,
    navigationTarget: "/accounting/fiscal-config",
    helpText: "Accounting is enabled but one or more default account mappings (cash, bank, receivable, income) are unset.",
    suggestedResolution: "Complete the fiscal configuration's default account mappings.",
  },
  {
    systemKey: "default:DraftVouchersPending",
    rule: "draftVouchersPending",
    description: "Draft vouchers should be posted, approved, or cancelled",
    severity: "Info",
    blocking: false,
    navigationTarget: "/accounting/vouchers?status=Draft",
    helpText: "Draft vouchers don't affect the ledger yet — they're excluded from Trial Balance until posted.",
    suggestedResolution: "Review and post, submit for approval, or cancel each Draft voucher.",
  },
  {
    systemKey: "default:AssetsMissingDepreciationThisYear",
    rule: "assetsMissingDepreciationThisYear",
    description: "Every active asset should have a depreciation run for the current Financial Year",
    severity: "Warning",
    blocking: false,
    navigationTarget: "/accounting/assets",
    helpText: "An asset with no depreciation run this year understates accumulated depreciation and overstates net book value.",
    suggestedResolution: "Run depreciation for each flagged asset before closing the Financial Year.",
  },
  {
    systemKey: "default:BankStatementsUnmatched",
    rule: "bankStatementsUnmatched",
    description: "Imported bank statement lines should be reconciled",
    severity: "Warning",
    blocking: false,
    navigationTarget: "/accounting/bank-accounts",
    helpText: "Unmatched statement lines mean the bank account's ledger balance hasn't been verified against the real bank statement.",
    suggestedResolution: "Run auto-suggest matching, then manually match or investigate the remainder.",
  },
  {
    systemKey: "default:LiabilitiesOverdue",
    rule: "liabilitiesOverdue",
    description: "Open liabilities past their due date should be settled or reviewed",
    severity: "Warning",
    blocking: false,
    navigationTarget: "/accounting/liabilities",
    helpText: "A liability past its due date may indicate a missed vendor/loan/tax payment.",
    suggestedResolution: "Record a payment against the liability, or update its due date if renegotiated.",
  },
];
