import { NextResponse } from "next/server";
import mongoose from "mongoose";
import connectDB from "@/lib/mongodb";
import { requireAccountingClose } from "@/lib/authz";
import Bill from "@/models/Bill";
import Transaction from "@/models/Transaction";
import Member from "@/models/Member";
import Asset from "@/models/Asset";
import JournalLine from "@/models/JournalLine";
import Voucher from "@/models/Voucher";

// POST /api/accounting/lab/reset — wipes the simulated data for THIS society so
// the master simulator can be replayed from a clean slate.
//
// Deliberately NOT destructive to configuration: the Financial Year, Chart of
// Accounts, posting rules, validation rules and schedules all survive, because
// those are the thing under test. Only the transactional artefacts generated by
// a simulator run are removed.
//
// Requires an explicit { confirm: "RESET" } body so it can never fire by
// accident from a stray click or a page refresh.
export async function POST(request) {
  const auth = requireAccountingClose(request);
  if (!auth.valid) return auth;
  try {
    await connectDB();
    const societyId = auth.user.societyId;
    const body = await request.json().catch(() => ({}));

    if (body.confirm !== "RESET") {
      return NextResponse.json(
        { error: 'Send { "confirm": "RESET" } to confirm this destructive action.' },
        { status: 400 },
      );
    }

    const session = await mongoose.startSession();
    const deleted = {};
    try {
      await session.withTransaction(async () => {
        const vouchers = await Voucher.find({ societyId }).select("_id").session(session).lean();
        const voucherIds = vouchers.map((v) => v._id);

        deleted.journalLines = (
          await JournalLine.deleteMany({ societyId }, { session })
        ).deletedCount;
        deleted.vouchers = (await Voucher.deleteMany({ societyId }, { session })).deletedCount;
        deleted.bills = (await Bill.deleteMany({ societyId }, { session })).deletedCount;
        deleted.transactions = (
          await Transaction.deleteMany({ societyId }, { session })
        ).deletedCount;
        deleted.assets = (await Asset.deleteMany({ societyId }, { session })).deletedCount;

        // Clear the member-side running balances the simulator moves.
        const res = await Member.updateMany(
          { societyId },
          { $set: { advanceCredit: 0, outstandingBalance: 0 } },
          { session },
        );
        deleted.membersReset = res.modifiedCount;
        deleted.voucherIdsTouched = voucherIds.length;
      });
    } finally {
      await session.endSession();
    }

    return NextResponse.json({
      reset: true,
      deleted,
      note: "Financial Year, Chart of Accounts and rule registries were preserved.",
    });
  } catch (error) {
    console.error("Lab reset error:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: error.status || 500 },
    );
  }
}
