"use client";

import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "@/lib/api-client";
import styles from "@/styles/Dashboard.module.css";
import gridStyles from "@/styles/BillingGrid.module.css";
import { produce } from "immer";

export default function SocietyConfigPage() {
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState({
    name: "",
    registrationNo: "",
    address: "",
    config: {
      interestRate: 0,
      serviceTaxRate: 0,
      billPushDay: 1,
      interestCalculationMethod: "SIMPLE",
      interestCompoundingFrequency: "MONTHLY",
      interestAfterDays: 15,
      interestActivationMode: "VIEW",
      billGenerationMode: "MANUAL",
      billAutoGenerateDay: 1,
    },
  });
  const [errors, setErrors] = useState({});
  const [successMessage, setSuccessMessage] = useState("");
  const [templateFile, setTemplateFile] = useState(null);
  const [uploadingTemplate, setUploadingTemplate] = useState(false);

  const { data: societyData, isLoading } = useQuery({
    queryKey: ["society-config"],
    queryFn: () => apiClient.get("/api/society/config"),
  });

  useEffect(() => {
    if (societyData?.society) {
      const c = societyData.society.config || {};
      setFormData({
        name: societyData.society.name || "",
        registrationNo: societyData.society.registrationNo || "",
        address: societyData.society.address || "",
        config: {
          interestRate: c.interestRate ?? 0,
          serviceTaxRate: c.serviceTaxRate ?? 0,
          billPushDay: c.billPushDay ?? 1,
          interestCalculationMethod: c.interestCalculationMethod ?? "SIMPLE",
          interestCompoundingFrequency: c.interestCompoundingFrequency ?? "MONTHLY",
          interestAfterDays: c.interestAfterDays ?? 15,
          interestActivationMode: c.interestActivationMode ?? "VIEW",
          billGenerationMode: c.billGenerationMode ?? "MANUAL",
          billAutoGenerateDay: c.billAutoGenerateDay ?? 1,
        },
      });
    }
  }, [societyData]);

  const updateMutation = useMutation({
    mutationFn: (data) => apiClient.put("/api/society/update", data),
    onSuccess: (data) => {
      setSuccessMessage("✅ Society configuration updated successfully!");

      // ✅ UPDATE FORM STATE WITH SERVER RESPONSE
      if (data.society) {
        const c = data.society.config || {};
        setFormData({
          name: data.society.name || "",
          registrationNo: data.society.registrationNo || "",
          address: data.society.address || "",
          config: {
            interestRate: c.interestRate ?? 0,
            serviceTaxRate: c.serviceTaxRate ?? 0,
            billPushDay: c.billPushDay ?? 1,
            interestCalculationMethod: c.interestCalculationMethod ?? "SIMPLE",
            interestCompoundingFrequency: c.interestCompoundingFrequency ?? "MONTHLY",
            interestAfterDays: c.interestAfterDays ?? 15,
            interestActivationMode: c.interestActivationMode ?? "VIEW",
            billGenerationMode: c.billGenerationMode ?? "MANUAL",
            billAutoGenerateDay: c.billAutoGenerateDay ?? 1,
          },
        });
      }

      queryClient.invalidateQueries(["society-config"]);
      setTimeout(() => setSuccessMessage(""), 5000);
    },
    onError: (error) => {
      setErrors({ submit: error.message });
    },
  });
  const handleTemplateUpload = async () => {
    if (!templateFile) {
      alert("Please select a PDF file");
      return;
    }

    setUploadingTemplate(true);
    try {
      const formData = new FormData();
      formData.append("template", templateFile);

      const response = await fetch("/api/society/upload-template", {
        method: "POST",
        body: formData,
      });

      const result = await response.json();

      if (response.ok) {
        alert("Template uploaded successfully!");
        setTemplateFile(null);
        queryClient.invalidateQueries(["society-config"]);
      } else {
        alert(result.error || "Upload failed");
      }
    } catch (error) {
      console.error("Upload error:", error);
      alert("Failed to upload template");
    } finally {
      setUploadingTemplate(false);
    }
  };

  const handleDeleteTemplate = async () => {
    if (!confirm("Delete uploaded template and use default?")) return;

    try {
      const response = await fetch("/api/society/upload-template", {
        method: "DELETE",
      });

      if (response.ok) {
        alert("Template deleted");
        queryClient.invalidateQueries(["society-config"]);
      }
    } catch (error) {
      alert("Failed to delete template");
    }
  };
  const handleChange = (path, value) => {
    setFormData((prev) =>
      produce(prev, (draft) => {
        const keys = path.split(".");
        let current = draft;

        // Navigate to the parent of the target key
        for (let i = 0; i < keys.length - 1; i++) {
          if (!current[keys[i]]) {
            current[keys[i]] = {}; // Create if doesn't exist
          }
          current = current[keys[i]];
        }

        // Set the final value
        current[keys[keys.length - 1]] = value;
        console.log(`✅ Updated ${path} to:`, value);
      }),
    );

    if (errors[path]) {
      setErrors((prev) => ({ ...prev, [path]: "" }));
    }
  };

  const validate = () => {
    const newErrors = {};
    if (!formData.name || formData.name.trim().length < 2)
      newErrors.name = "Society name must be at least 2 characters";
    if (formData.config.interestRate < 0 || formData.config.interestRate > 100)
      newErrors.interestRate = "Interest rate must be between 0 and 100";
    if (
      formData.config.serviceTaxRate < 0 ||
      formData.config.serviceTaxRate > 100
    )
      newErrors.serviceTaxRate = "Service tax rate must be between 0 and 100";
    const afterDays = formData.config.interestAfterDays;
    if (afterDays === undefined || afterDays < 0 || afterDays > 365)
      newErrors.interestAfterDays = "Interest after days must be 0–365";
    if (formData.config.billGenerationMode === "AUTOMATIC") {
      const autoDay = formData.config.billAutoGenerateDay;
      if (!autoDay || autoDay < 1 || autoDay > 5)
        newErrors.billAutoGenerateDay = "Auto generate day must be 1–5";
    }
    const pushDay = formData.config.billPushDay;
    if (!pushDay || pushDay < 1 || pushDay > 31)
      newErrors.billPushDay = "Bill push day must be between 1 and 31";
    return newErrors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const validationErrors = validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    try {
      await updateMutation.mutateAsync({
        ...formData,
      });
      // ✅ CRITICAL: Update state with response data
      // This ensures the form shows the saved values
      console.log("✅ Save successful, state updated");
    } catch (error) {
      console.error("❌ Save failed:", error);
      setErrors({ submit: error.message });
    }
  };

  if (isLoading) {
    return (
      <div
        style={{ display: "flex", justifyContent: "center", padding: "40px" }}
      >
        <div className="loading-spinner"></div>
      </div>
    );
  }

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <div className={styles.pageHeader}>
          <div>
            <h1 className={styles.pageTitle}>Society Configuration</h1>
            <p className={styles.pageSubtitle}>
              Manage society details and financial parameters
            </p>
          </div>
          <div>
            <button
              type="button"
              onClick={() => window.location.reload()}
              className="btn btn-secondary"
            >
              🔄 Reset Changes
            </button>
            <button
              type="submit"
              className="btn btn-success"
              disabled={updateMutation.isPending}
            >
              {updateMutation.isPending ? (
                <>
                  <span className="loading-spinner"></span>
                  Saving...
                </>
              ) : (
                <>💾 Save Configuration</>
              )}
            </button>
          </div>
        </div>

        {successMessage && (
          <div
            className="toast toast-success"
            style={{ position: "relative", marginBottom: "var(--spacing-lg)" }}
          >
            {successMessage}
          </div>
        )}

        {errors.submit && (
          <div className={gridStyles.errorList}>
            <div className={gridStyles.errorListTitle}>❌ Update Failed</div>
            <div>{errors.submit}</div>
          </div>
        )}

        <div className={styles.contentCard}>
          <div className={styles.cardHeader}>
            <h2 className={styles.cardTitle}>Basic Information</h2>
          </div>

          <div className={gridStyles.configForm}>
            <div className={gridStyles.formGroup}>
              <label className="label">Society Name *</label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => handleChange("name", e.target.value)}
                className={`input ${errors.name ? "input-error" : ""}`}
                placeholder="Green Valley Apartments"
              />
              {errors.name && <p className="error-text">{errors.name}</p>}
            </div>

            <div className={gridStyles.formRow}>
              <div className={gridStyles.formGroup}>
                <label className="label">Registration Number</label>
                <input
                  type="text"
                  value={formData.registrationNo}
                  onChange={(e) =>
                    handleChange("registrationNo", e.target.value)
                  }
                  className="input"
                  placeholder="REG/2024/1234"
                />
              </div>
            </div>

            <div className={gridStyles.formGroup}>
              <label className="label">Address</label>
              <textarea
                value={formData.address}
                onChange={(e) => handleChange("address", e.target.value)}
                className="input"
                rows="3"
                placeholder="Complete society address"
              />
            </div>
          </div>
        </div>

        <div className={styles.contentCard}>
          <div className={styles.cardHeader}>
            <h2 className={styles.cardTitle}>Financial Parameters</h2>
          </div>

          <div className={gridStyles.formRow}>
            {/* Interest Rate on Arrears */}
            <div className={gridStyles.formGroup}>
              <label className="label">
                Interest Rate on Arrears (% per annum) *
              </label>
              <input
                type="number"
                min="0"
                max="100"
                step="0.01"
                value={formData.config.interestRate}
                onChange={(e) =>
                  handleChange(
                    "config.interestRate",
                    parseFloat(e.target.value) || 0,
                  )
                }
                className={`input ${errors.interestRate ? "input-error" : ""}`}
                placeholder="21.00"
              />
              {errors.interestRate && (
                <p className="error-text">{errors.interestRate}</p>
              )}
              <span
                style={{
                  fontSize: "var(--font-xs)",
                  color: "var(--text-secondary)",
                }}
              >
                Annual interest rate on overdue payments (e.g., 21% p.a.)
              </span>
            </div>

            <div className="config-field">
              <label>Interest Rounding</label>
              <select
                value={formData.config.interestRounding || "TWO_DECIMAL"}
                onChange={(e) =>
                  handleChange("config.interestRounding", e.target.value)
                }
                className="input"
              >
                <option value="TWO_DECIMAL">
                  2 Decimal (e.g. 10.256 → 10.26)
                </option>
                <option value="ROUND_UP">
                  Round Up to whole rupee (e.g. 10.001 → 11)
                </option>
              </select>
              <p className="hint">
                Society never spares even ₹0.01 — use Round Up
              </p>
            </div>

            <div className="config-field">
              <label>Interest Use Mode</label>
              <select
                value={formData.config.interestUseMode || "OLDEST_FIRST"}
                onChange={(e) =>
                  handleChange("config.interestUseMode", e.target.value)
                }
                className="input"
              >
                <option value="OLDEST_FIRST">
                  Oldest First — clear oldest period's interest first
                </option>
                <option value="TOTAL">
                  Total Pool — treat all interest as one bucket
                </option>
              </select>
            </div>

            <div className="config-field">
              <label>Member Payment Breakdown Visible</label>
              <input
                type="checkbox"
                checked={
                  formData.config.memberPaymentBreakdownVisible !== false
                }
                onChange={(e) =>
                  handleChange(
                    "config.memberPaymentBreakdownVisible",
                    e.target.checked,
                  )
                }
              />
              <span>Show members how much goes to interest vs principal</span>
            </div>

            <div className="config-field">
              <label>Adjustment Application Mode</label>
              <select
                value={
                  formData.config.adjustmentApplicationMode || "INTEREST_FIRST"
                }
                onChange={(e) =>
                  handleChange(
                    "config.adjustmentApplicationMode",
                    e.target.value,
                  )
                }
                className="input"
              >
                <option value="INTEREST_FIRST">Interest First (default)</option>
                <option value="PRINCIPAL_FIRST">Principal First</option>
              </select>
            </div>

            <div className="config-field">
              <label>Interest Trigger Timing</label>
              <select
                value={formData.config.interestTriggerTiming || "NEXT_DAY"}
                onChange={(e) =>
                  handleChange("config.interestTriggerTiming", e.target.value)
                }
                className="input"
              >
                <option value="NEXT_DAY">
                  Next Day (interest starts day after grace ends)
                </option>
                <option value="SAME_DAY">
                  Same Day (interest starts on grace end day)
                </option>
              </select>
            </div>
            {/* Service Tax Rate */}
            <div className={gridStyles.formGroup}>
              <label className="label">Service Tax Rate (%)</label>
              <input
                type="number"
                min="0"
                max="100"
                step="0.01"
                value={formData.config.serviceTaxRate}
                onChange={(e) =>
                  handleChange(
                    "config.serviceTaxRate",
                    parseFloat(e.target.value) || 0,
                  )
                }
                className={`input ${
                  errors.serviceTaxRate ? "input-error" : ""
                }`}
                placeholder="2.00"
              />
              {errors.serviceTaxRate && (
                <p className="error-text">{errors.serviceTaxRate}</p>
              )}
              <span
                style={{
                  fontSize: "var(--font-xs)",
                  color: "var(--text-secondary)",
                }}
              >
                Tax applied on total charges (e.g., GST 2%)
              </span>
            </div>

            {/* Billing timing defaults — overridable per-run in Generate Bills page */}
            <div style={{ gridColumn: "1 / -1", background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: "8px", padding: "0.75rem 1rem", marginBottom: "0.5rem", fontSize: "0.8rem", color: "#1e40af" }}>
              💡 These are <strong>default values</strong>. You can override them per billing run in the <strong>Generate Bills</strong> page without changing these global defaults.
            </div>

            {/* ── Interest Activation Settings ─────────────────────────────── */}
            <div style={{ gridColumn: "1 / -1", border: "1px solid #c7d2fe", borderRadius: "10px", padding: "1.25rem", background: "#f5f3ff", marginBottom: "0.5rem" }}>
              <h3 style={{ margin: "0 0 1rem", fontSize: "0.95rem", color: "#4338ca", fontWeight: 700 }}>
                Interest Activation Settings
              </h3>

              <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "1.25rem" }}>
                <label style={{ fontSize: "0.875rem", fontWeight: 600, color: "#374151", whiteSpace: "nowrap" }}>
                  Interest After
                </label>
                <input
                  type="number"
                  min="0"
                  max="365"
                  value={formData.config.interestAfterDays}
                  onChange={(e) => handleChange("config.interestAfterDays", parseInt(e.target.value) || 0)}
                  style={{ width: "80px", padding: "0.4rem 0.6rem", border: "1px solid #c7d2fe", borderRadius: "6px", fontSize: "0.875rem", textAlign: "center" }}
                />
                <span style={{ fontSize: "0.875rem", color: "#6b7280" }}>days</span>
                {errors.interestAfterDays && <span style={{ color: "#dc2626", fontSize: "0.8rem" }}>{errors.interestAfterDays}</span>}
              </div>

              <div style={{ display: "flex", gap: "2rem", alignItems: "flex-start" }}>
                {[
                  { value: "VIEW", label: "View Mode", hint: "Warning only until next billing cycle. Interest applied at next bill generation." },
                  { value: "APPLICABLE", label: "Applicable Mode", hint: "Unpaid principal becomes interest-eligible after the configured days." },
                ].map(({ value, label, hint }) => (
                  <label key={value} style={{ display: "flex", alignItems: "flex-start", gap: "0.5rem", cursor: "pointer" }}>
                    <input
                      type="radio"
                      name="interestActivationMode"
                      value={value}
                      checked={formData.config.interestActivationMode === value}
                      onChange={() => handleChange("config.interestActivationMode", value)}
                      style={{ marginTop: "3px" }}
                    />
                    <div>
                      <div style={{ fontSize: "0.875rem", fontWeight: 600, color: "#1f2937" }}>{label}</div>
                      <div style={{ fontSize: "0.75rem", color: "#6b7280", lineHeight: 1.4 }}>{hint}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* ── Bill Generation Mode ──────────────────────────────────────── */}
            <div style={{ gridColumn: "1 / -1", border: "1px solid #bbf7d0", borderRadius: "10px", padding: "1.25rem", background: "#f0fdf4" }}>
              <h3 style={{ margin: "0 0 1rem", fontSize: "0.95rem", color: "#166534", fontWeight: 700 }}>
                Bill Generation Mode
              </h3>

              <div style={{ display: "flex", gap: "2rem", alignItems: "flex-start", marginBottom: formData.config.billGenerationMode === "AUTOMATIC" ? "1rem" : 0 }}>
                {[
                  { value: "MANUAL", label: "Manual", hint: "Admin downloads template, fills payments, uploads to trigger generation." },
                  { value: "AUTOMATIC", label: "Automatic", hint: "System auto-generates bills on configured day (1st–5th of month)." },
                ].map(({ value, label, hint }) => (
                  <label key={value} style={{ display: "flex", alignItems: "flex-start", gap: "0.5rem", cursor: "pointer" }}>
                    <input
                      type="radio"
                      name="billGenerationMode"
                      value={value}
                      checked={formData.config.billGenerationMode === value}
                      onChange={() => handleChange("config.billGenerationMode", value)}
                      style={{ marginTop: "3px" }}
                    />
                    <div>
                      <div style={{ fontSize: "0.875rem", fontWeight: 600, color: "#1f2937" }}>{label}</div>
                      <div style={{ fontSize: "0.75rem", color: "#6b7280", lineHeight: 1.4 }}>{hint}</div>
                    </div>
                  </label>
                ))}
              </div>

              {formData.config.billGenerationMode === "AUTOMATIC" && (
                <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginTop: "1rem", paddingTop: "1rem", borderTop: "1px solid #bbf7d0" }}>
                  <label style={{ fontSize: "0.875rem", fontWeight: 600, color: "#374151" }}>Auto Generate Day</label>
                  <input
                    type="number"
                    min="1"
                    max="5"
                    value={formData.config.billAutoGenerateDay}
                    onChange={(e) => handleChange("config.billAutoGenerateDay", parseInt(e.target.value) || 1)}
                    style={{ width: "70px", padding: "0.4rem 0.6rem", border: "1px solid #86efac", borderRadius: "6px", fontSize: "0.875rem", textAlign: "center" }}
                  />
                  <span style={{ fontSize: "0.8rem", color: "#6b7280" }}>(allowed: 1–5 only)</span>
                  {errors.billAutoGenerateDay && <span style={{ color: "#dc2626", fontSize: "0.8rem" }}>{errors.billAutoGenerateDay}</span>}
                </div>
              )}
            </div>

            {/* Bill Push Day — when bills become visible to members */}
            <div className={gridStyles.formGroup}>
              <label className="label">
                Bill Visible to Members From (Day)
              </label>
              <input
                type="number"
                min={1}
                max={31}
                value={formData.config?.billPushDay ?? 1}
                onChange={(e) => {
                  const value = !e.target.value ? 1 : parseInt(e.target.value);
                  handleChange("config.billPushDay", value);
                }}
                className={`input${errors.billPushDay ? " input-error" : ""}`}
                placeholder="1"
              />
              {errors.billPushDay && (
                <p className="error-text">{errors.billPushDay}</p>
              )}
              <span
                style={{
                  fontSize: "var(--font-xs)",
                  color: "var(--text-secondary)",
                }}
              >
                Day of month when bills become visible on member dashboards.
                Bills generated before this date are stored as <strong>Scheduled</strong>.
              </span>
            </div>

            {/* Interest Calculation Method */}
            <div className={gridStyles.formGroup}>
              <label className="label">Interest Calculation Method</label>
              <select
                value={formData.config.interestCalculationMethod}
                onChange={(e) =>
                  handleChange(
                    "config.interestCalculationMethod",
                    e.target.value,
                  )
                }
                className="input"
              >
                <option value="SIMPLE">Simple Interest</option>
                <option value="COMPOUND">Compound Interest</option>
              </select>
              <span
                style={{
                  fontSize: "var(--font-xs)",
                  color: "var(--text-secondary)",
                }}
              >
                How interest is calculated on overdue amounts
              </span>
            </div>

            {/* Compounding Frequency */}
            <div className={gridStyles.formGroup}>
              <label className="label">Interest Compounding Frequency</label>
              <select
                value={formData.config.interestCompoundingFrequency}
                onChange={(e) =>
                  handleChange(
                    "config.interestCompoundingFrequency",
                    e.target.value,
                  )
                }
                className="input"
                disabled={
                  formData.config.interestCalculationMethod === "SIMPLE"
                }
              >
                <option value="MONTHLY">Monthly</option>
              </select>

              <span
                style={{
                  fontSize: "var(--font-xs)",
                  color: "var(--text-secondary)",
                }}
              >
                Only applies when Compound Interest is selected
              </span>
            </div>
          </div>
        </div>
      </form>
    </div>
  );
}
